name: My CI Workflow

on:
  workflow_call:
    inputs:
      foo:
        description: 'Please approve the PR'
        required: true
        default: 'bar'
  pull_request_review:
    types: [submitted]

jobs:
  build-and-push:
    # Only run the job if it's an approval review
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mkarimi20/alpine2:latest
  
