name: My CI Workflows

on:
  workflow_call:
    inputs:
      my_var:
        required: true
        type: string
  # push:
  #   branches: [ main ]

jobs:
  deploy:
    name: ubuntu
    runs-on: ubuntu-latest
    environment: 
      name: Approve-deployment
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Set environment variable
      run: |
        echo "Running Terraform Apply with MY_VAR: ${{ inputs.my_var }}"
        echo "PR_APM=${{ inputs.my_var }}" >> $GITHUB_ENV
    - name: setting variable
      run: |
        env
    - name: Checkout
      uses: actions/checkout@main
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    # - name: Configure AWS credentials from Test account
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     role-to-assume: arn:aws:iam::781827335746:role/action-runner
    #     aws-region: us-east-2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mkarimi20/alpine2:latest
  
