name: My CI Workflow

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    # # Only run the job if it's an approval review
    # if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: mkarimi20/alpine2:latest
  
