---
name: runner-eks
on:
  push:
    branches: [ main ]    
jobs:
  deploy:
    name: ubuntu
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: setting variable
      run: |
        PR_APM="${{ github.head_ref }}"
        echo "APM id for this action is $PR_APM"
        echo "PR_APM=$PR_APM" >> $GITHUB_ENV
    - name: Checkout
      uses: actions/checkout@main
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    # - name: Configure AWS credentials from Test account
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     role-to-assume: arn:aws:iam::781827335746:role/action-runner
    #     aws-region: us-east-2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -  name: Build and push
       uses: docker/build-push-action@v2
       with:
         push: true
         tags: mkarimi20/alpine2:latest

      
      
